org: ezeikel
app: five-yards-api
service: five-yards-apollo-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  environment:
    FRONTEND_URL: ${param:frontend-url, 'http://localhost:3000'}
    DATABASE_URL: ${param:database-url}
    SENTRY_DSN: ${param:sentry-dsn}
    APP_SECRET: ${param:app-secret}
    STRIPE_SECRET_KEY: ${ssm:/five-yards/keys/stripe}
    MAIL_HOST: ${param:mail-host}
    MAIL_PORT: 2525
    MAIL_USER: ${param:mail-user}
    MAIL_PASS: ${param:mail-pass}
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

params:
  prod:
    frontend-url: 'https://fiveyards.co'
    domain: 'api.fiveyards.co'
  staging:
    frontend-url: 'https://staging.fiveyards.co'
    domain: 'staging.api.fiveyards.co'
  dev:
    frontend-url: 'https://develop.fiveyards.co'
    domain: 'develop.api.fiveyards.co'

plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline-variables
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${param:domain}
    basePath: graphql
    createRoute53Record: true
  serverless-offline:
    printOutput: true
    prefix: graphql
    httpPort: 7000
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'yarn' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

functions:
  graphql:
    handler: src/handlers/graphql.handler
    events:
      - http:
          path: /
          method: post
          cors:
            origins:
              - https://*.fiveyards.co
              - https://studio.apollographql.com
            headers:
              - Authorization
              - Content-Type
            allowCredentials: true
      - http:
          path: /
          method: get
          cors:
            origins:
              - https://*.fiveyards.co
              - https://studio.apollographql.com
            headers:
              - Authorization
              - Content-Type
            allowCredentials: true
