org: ezeikel
app: five-yards-api
service: apollo-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  environment:
    FRONTEND_URL: 'https://fiveyards.co'
    DATABASE_URL: ${ssm:/five-yards/keys/mongodb}
    SENTRY_DSN: ${ssm:/five-yards/keys/sentry}
    APP_SECRET: ${ssm:/five-yards/keys/app-secret}
    STRIPE_SECRET_KEY: ${ssm:/five-yards/keys/stripe}
    MAIL_HOST: 'smtp.postmarkapp.com'
    MAIL_PORT: 2525
    MAIL_USER: ${ssm:/five-yards/keys/postmark}
    MAIL_PASS: ${ssm:/five-yards/keys/postmark}
  apiGateway:
    binaryMediaTypes:
      - '*/*'

plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline-variables
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.fiveyards.co
    basePath: graphql
    createRoute53Record: true
  serverless-offline:
    printOutput: true
    prefix: graphql
    httpPort: 7000
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'yarn' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

functions:
  graphql:
    handler: src/handlers/graphql.handler
    events:
      - http:
          path: /
          method: post
          cors:
            origin: https://www.fiveyards.co
            headers:
              - Authorization
              - Content-Type
            allowCredentials: true
      - http:
          path: /
          method: get
          cors:
            origin: https://www.fiveyards.co
            headers:
              - Authorization
              - Content-Type
            allowCredentials: true
